version: '3.3'
services:
  db:
    image: mysql:5.7
    environment:
      - MYSQL_DATABASE=mapknitter
      - MYSQL_USER=mapknitter
      - MYSQL_PASSWORD=mapknitter
      - MYSQL_RANDOM_ROOT_PASSWORD=true
    volumes:
      - ../mysql:/var/lib/mysql
      - ../dump:/docker-entrypoint-initdb.d
  web:
    image: mapknitter-dev
    build:
      context: .
      dockerfile: Dockerfile.txt
    environment:
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_USER}
      - DB_NAME=${DB_NAME}
      - DB_PASS=${DB_PASS}
      - RAILS_ENV=${RAILS_ENV}
    volumes:
      - .:/app
      - bundle_cache:/usr/local/bundle
      - bower_cache:/app/public/lib
    ports:
      - $PORT:3000
    depends_on:
      - db

volumes:
  bundle_cache:
  bower_cache:
