development:
  adapter: mysql
  database: cartagen_development
  username: root
  password: 

production:
  adapter: mysql
  database: cartagen_production
  username: root
  password: 

test:
  adapter: mysql
  database: cartagen_test
  username: root
  password: 
